export {default as services1} from 'public/services.svg'
export {default as services2} from 'public/services2.svg'
export {default as services3} from 'public/services3.svg'
export {default as services4} from 'public/services4.svg'
export {default as services5} from 'public/services5.svg'
export {default as services6} from 'public/services6.svg'
export {default as services7} from 'public/services7.svg'
export { default as services8 } from 'public/services8.svg'
export {default as patients} from 'public/pat1.svg'
export {default as Logo} from 'public/logo.jpg'
export {default as Tratamientos} from 'public/Tratamiento.svg'
export {default as TipoTratamiento} from 'public/TipoTratamiento.svg'
export {default as TipoProd1} from 'public/TipoProd1.svg'
export { default as TipoProd2 } from 'public/TipoProd2.svg'
export { default as consultaexterna } from 'public/consultaexterna.svg'
export { default as clinicadelamujer } from 'public/clinicadelamujer.svg'
export { default as controlprenatal } from 'public/controlprenatal.svg'
export { default as colposcopia } from 'public/colposcopia.svg'
export { default as papanicolaou } from 'public/papanicolaou.svg'
export { default as postoperacion } from 'public/postoperacion.svg'
export { default as proced1 } from 'public/proced1.svg'
export { default as proced2 } from 'public/proced2.svg'
export { default as proced3 } from 'public/proced3.svg'
export { default as paciente } from 'public/patient.svg'
export { default as crioterapiaimg } from 'public/Crioterapia.png'
export { default as colposcopiadiag } from 'public/Colposcopia Diag.png'
export {default as citas} from 'public/agendado.svg'


